### getting comments

GET http://localhost:4001/posts/1/comments


### posting comments

POST  http://localhost:4001/posts/11/comments
Content-Type: application/json

{
    "content": "på en råta här vi skickar räven"
}
